import { Product } from './types';

export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Solitaire Diamond Ring',
    price: 3500,
    category: 'ring',
    image: 'https://picsum.photos/seed/ring1/600/600',
    description: 'A timeless classic featuring a brilliant round-cut diamond set in platinum.',
    metal: 'Platinum',
    stone: 'Diamond',
  },
  {
    id: '2',
    name: 'Vintage Halo Engagement Ring',
    price: 4200,
    category: 'ring',
    image: 'https://picsum.photos/seed/ring2/600/600',
    description: 'Intricate milgrain detailing surrounds a cushion-cut center stone.',
    metal: '18k Gold',
    stone: 'Diamond',
  },
  {
    id: '3',
    name: 'Sapphire Pendant Necklace',
    price: 1200,
    category: 'necklace',
    image: 'https://picsum.photos/seed/neck1/600/600',
    description: 'A deep blue sapphire suspended from a delicate gold chain.',
    metal: '18k Gold',
    stone: 'Sapphire',
  },
  {
    id: '4',
    name: 'Diamond Stud Earrings',
    price: 1800,
    category: 'earrings',
    image: 'https://picsum.photos/seed/ear1/600/600',
    description: 'Essential luxury. Perfectly matched round diamonds in a four-prong setting.',
    metal: 'Platinum',
    stone: 'Diamond',
  },
  {
    id: '5',
    name: 'Tennis Bracelet',
    price: 5500,
    category: 'bracelet',
    image: 'https://picsum.photos/seed/brace1/600/600',
    description: 'A continuous line of brilliance for the wrist.',
    metal: 'Platinum',
    stone: 'Diamond',
  },
  {
    id: '6',
    name: 'Rose Gold Eternity Band',
    price: 2100,
    category: 'ring',
    image: 'https://picsum.photos/seed/ring3/600/600',
    description: 'Pave-set diamonds encircle the finger in warm rose gold.',
    metal: 'Rose Gold',
    stone: 'Diamond',
  },
   {
    id: '7',
    name: 'Emerald Cut Three-Stone Ring',
    price: 6800,
    category: 'ring',
    image: 'https://picsum.photos/seed/ring4/600/600',
    description: 'A stunning emerald cut diamond flanked by tapered baguettes.',
    metal: 'Platinum',
    stone: 'Diamond',
  },
  {
    id: '8',
    name: 'Pearl Drop Earrings',
    price: 850,
    category: 'earrings',
    image: 'https://picsum.photos/seed/ear2/600/600',
    description: 'Lustrous freshwater pearls hanging from diamond accents.',
    metal: '18k Gold',
  }
];

export const CATEGORIES = [
  { id: 'ring', label: 'Engagement Rings', image: 'https://picsum.photos/seed/catring/400/300' },
  { id: 'necklace', label: 'Necklaces', image: 'https://picsum.photos/seed/catneck/400/300' },
  { id: 'earrings', label: 'Earrings', image: 'https://picsum.photos/seed/catear/400/300' },
  { id: 'bracelet', label: 'Bracelets', image: 'https://picsum.photos/seed/catbrace/400/300' },
];